import { Chart, Palette } from "@/public/icons";

const ServiceBundles = {
  digital: [
    {
      icon: <Chart />,
      bundle: "Basic Package",
      price: "$499",
      description:
        "Access to basic copywriting services, for small businesses or startups",
      features: [
        "Keyword Research",
        "On-Page SEO",
        "Link Building",
        "Technical SEO Audit",
        "Content Creation and Optimization",
        "Local SEO",
        "Mobile SEO",
        "Voice Search Optimization",
        "Schema Markup Implementation",
        "Site Speed Optimization",
        "Image Optimization",
        "SEO Competitor Analysis",
        "User Experience (UX) Enhancements",
        "Analytics and Reporting",
        "SEO Training and Consultation",
      ],
    },
    {
      icon: <Chart />,
      bundle: "Standard Package",
      price: "$499",
      description:
        "Ideal for businesses seeking to take their marketing copies to the next level",
      features: [
        "Campaign Planning",
        "Ad Management",
        "Performance Reporting",
        "Audience Research and Segmentation",
        "Creative Design and Development",
        "A/B Testing",
        "Landing Page Optimization",
        "Budget Allocation and Management",
        "Remarketing/Retargeting Strategies",
        "Social Media Advertising",
        "Influencer Marketing",
        "Content Marketing",
        "Email Marketing Campaigns",
        "Campaign Automation Tools",
        "Competitive Analysis and Benchmarking",
      ],
    },
    {
      icon: <Chart />,
      bundle: "Premium Package",
      price: "$499",
      description:
        "Perfect for businesses with need for a full spectrum of copywriting services ",
      features: [
        "Storefront Design",
        "Product Listing",
        "Payment Integration",
        "SEO Optimization",
        "Mobile Optimization",
        "User Experience (UX) Design",
        "Customer Support Integration",
        "Inventory Management System",
        "Marketing Tools Integration",
        "Security Features",
        "Shipping and Fulfillment Integration",
        "Customer Reviews and Ratings",
        "Loyalty Programs and Discounts",
        "Content Management System (CMS)",
      ],
    },
  ],
  creative: [
    {
      icon: <Palette />,
      bundle:
        "For businesses establishing an online presence with essential blogging services",
      price: "$20",
      description:
        "Ideal for growing businesses building a stronger online presence",
      features: [
        "Logo Design",
        "Brand Guidelines",
        "Business Card Design",
        "Stationery Design (Letterhead, Envelope)",
        "Packaging Design",
        "Website Design Consistency with Branding",
        "Signage and Display Design",
        "Uniform and Merchandise Design",
        "Brand Voice Development",
        "Brand Storytelling",
        "Brand Identity Consultation",
        "Brand Audit and Analysis",
        "Brand Reputation Management",
        "Brand Awareness Campaigns",
        "Brand Partnership Development",
      ],
    },
    {
      icon: <Palette />,
      bundle: "Social Media Content Creation",
      price: "$100",
      description:
        "For established businesses seeking to dominate their industry’s online space",
      features: [
        "Post Design",
        "Content Calendar",
        "Engagement Analytics",
        "Social Media Strategy Development",
        "Platform-Specific Content Creation",
        "Community Management",
        "Influencer Collaboration",
        "Social Media Advertising",
        "Hashtag Research and Optimization",
        "Reputation Management",
        "User-Generated Content Promotion",
        "Live Streaming and Video Content",
        "Competitor Analysis",
        "Social Media Contests and Giveaways",
        "Regular Performance Reports",
      ],
    },
    {
      icon: <Palette />,
      bundle: "Website Design Bundle",
      price: "$100",
      description: "For most businesses that want to optimize web queries",
      features: [
        "Custom Website Design",
        "Responsive Layout",
        "Basic SEO Optimization",
        "Content Management System Integration",
        "E-commerce Functionality",
        "Custom Graphics and Branding",
        "Social Media Integration",
        "Blog Setup",
        "Contact Form Integration",
        "Website Maintenance and Support",
        "Web Hosting and Domain Setup",
        "Security Features (SSL, Firewalls)",
        "Multilingual Support",
        "Analytics and Tracking Setup",
        "Performance Optimization",
      ],
    },
  ],
};

export default ServiceBundles;
