export { default as Arrow } from "./ash-arrow-down.svg";
export { default as AvatarProfile } from "./avatar_profile.svg";
export { default as ArrowBackIcon } from "./arrow-back-desktop.svg";
export { default as ArrowDown } from "./ash-arrow-down.svg";
export { default as AshArrowDown } from "./ash-arrow-down.svg";
export { default as AshArrowUp } from "./ash-arrow-up.svg";
export { default as AttachIcon } from "./attach.svg";
export { default as AvailableIcon } from "./available.svg";
// export { default as AvatarIcon } from "./avatar.svg"; // pending
export { default as BasicPackageIcon } from "./basic-package-icon.svg";
export { default as ThrashIcon } from "./bin.svg";
export { default as BlueArrowLeft } from "./blue-arrow-left.svg";
export { default as BlueArrowRight } from "./blue-arrow-right.svg";
export { default as BlueCheckIcon } from "./blue-check.svg";
export { default as BlueProfileIcon } from "./blue-profile.svg";
export { default as BlueProjectIcon } from "./blue-project.svg";
export { default as BlueSupportIcon } from "./blue-support.svg";
export { default as BlueTargetIcon } from "./blue-target.svg";
export { default as BlueUserIcon } from "./blue-user.svg";
export { default as CancelIcon } from "./cancel.svg";
export { default as Chart } from "./chart.svg";
export { default as Checked } from "./checked-checkbox.svg";
export { default as ProjectServiceIcon } from "./comprehensive.svg";
export { default as TailoredServiceIcon } from "./computer.svg";
export { default as ConfirmIcon } from "./confirm-icon.svg";
export { default as Crea8Star } from "./crea8-star.svg";
// export { default as CurvedArrow } from "./curved-arrow.svg";
export { default as DownloadIcon } from "./download.svg";
export { default as EmailAddressIcon } from "./email-address.svg";
export { default as EmailFieldIcon } from "./email-field.svg";
export { default as EyeCloseIcon } from "./eye-close.svg";
export { default as EyeOpenIcon } from "./eye-open.svg";
export { default as FacebookIcon } from "./facebook.svg";
export { default as GoogleIcon } from "./google.svg";
export { default as MobileToggle } from "./hamburger.svg";
// export { default as HighlightDown } from "./highlight-down.svg";
// export { default as HighlightDownMobile } from "./highlight-down-mobile.svg";
// export { default as HighlightUp } from "./highlight-up.svg";
// export { default as HighlightUpMobile } from "./highlight-up-mobile.svg";
// export { default as Highlight } from "./highlight.svg";
// export { default as HighlightMobile } from "./highlight-mobile.svg";
export { default as LightBulb } from "./lightbulb.svg";
export { default as LinkedInIcon } from "./linkedin.svg";
export { default as ListCheck } from "./list-check.svg";
export { default as Logo } from "./logo.svg";
export { default as LogoBlue } from "./logo-blue.svg";
export { default as NonAvailableIcon } from "./non-available.svg";
export { default as Palette } from "./palette.svg";
// export { default as Pencil } from "./pencil.svg"; // pending
export { default as PhoneNumberIcon } from "./phone-number.svg";
export { default as PremiumPackageIcon } from "./premium-package-icon.svg";
export { default as Rocket } from "./rocket.svg";
export { default as SearchIcon } from "./search.svg";
export { default as SecurePaymentServiceIcon } from "./secure.svg";
export { default as Smiley } from "./smiley.svg";
export { default as StandardPackageIcon } from "./standard-package-icon.svg";
export { default as StartProjectText } from "./start-project.svg";
export { default as SubmitBriefIcon } from "./submit-a-brief.svg";
export { default as ToolTipIcon } from "./tooltip.svg";
export { default as Unchecked } from "./unchecked-checkbox.svg";
export { default as UserProfilePhoto } from "./user-profile-picture.svg";
export { default as UserFriendlyServiceIcon } from "./user.svg";
export { default as LogoBlack } from "./logo-black.svg";
export { default as Copy } from "./copy.svg";
export { default as LinkIcon } from "./link-icon.svg";
export { default as Close } from "./multiply.svg";
export { default as Logout } from "./logout.svg";
export { default as SortIcon } from "./ash-arrow-down.svg";
export { default as CheckCircleIcon } from "./check-circle.svg";
export { default as CheckCircleIcon2 } from "./check-circle2.svg";
export { default as Icon } from "./vision-icon.svg";
export { default as PasswordNoMatchIcon } from "./password-no-match.svg";
export { default as PasswordMatchIcon } from "./password-match.svg";
export { default as EyeIcon } from "./eye-close.svg";

// export { default as ArrowDrawing } from "./arrow-drawing.svg";
// export { default as ArrowDrawingMobile } from "./arrow-drawing-mobile.svg";
export { default as TwitterIcon } from "./team-x.svg";
export { default as TeamLinkedIn } from "./team-linkedin.svg";
export { default as TeamFacebook } from "./team-fb.svg";
export { default as DemoIcon } from "./book.svg";
export { default as ResourceIcon } from "./file-cloud.svg";
export { default as WebinarIcon } from "./devices.svg";
export { default as BlogIcon } from "./box.svg";
export { default as GuideIcon } from "./gps.svg";
export { default as CreativeIcon } from "./creative.svg";
export { default as DigitalIcon } from "./digital.svg";
export { default as TopIcon } from "./lamp.svg";
export { default as BasicIcon } from "./basic.svg";
export { default as PremiumIcon } from "./premium.svg";
export { default as StandardIcon } from "./standard.svg";
export { default as Edit } from "./edit.svg";
export { default as BulbIcon } from "./bulb.svg";
export { default as ArrowRight } from "./arrow-right.svg";
export { default as SubmittedIcon } from "./submitted.svg";
export { default as ClockIcon } from "./clock.svg";
export { default as CalenderIcon } from "./calender.svg";
export { default as CameraIcon } from "./camera.svg";

// SOCIAL ICONS
export { default as XLogo } from "./x_icon.svg";
export { default as FacebookLogo } from "./facebook_icon.svg";
export { default as LinkedinLogo } from "./linkedin_icon.svg";
export { default as InstagramLogo } from "./instagram_icon.svg";

// BRAND ICONS
export { default as OppoLogo } from "./oppo_logo.svg";
export { default as GtBankLogo } from "./guaranty_trust_bank_logo.svg";
export { default as MtnLogo } from "./mtn_nigeria_logo.svg";
export { default as UbaBankLogo } from "./uba_bank_logo.svg";
export { default as AirpeaceLogo } from "./air_peace_logo.svg";

// DISPLAY ICONS
export { default as BrandDesignSVG } from "./brand_design_bulb.svg";
export { default as GraphicDesignsSVG } from "./graphic_designs_board.svg";
export { default as DigitalMarketingSVG } from "./digital_marketing_blocks.svg";
export { default as ContentWritingSVG } from "./content_writing_pad.svg";
export { default as AllInOneBundleSVG } from "./all_in_one_bundle_ship.svg";
