name: Build Mortgage Match Form FE

on:
  push:
    branches: [main, dev, dev-temp]

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # - name: Create an issue on failure
      #   if: failure()
      #   uses: actions/github-script@v7
      #   id: set-result
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const repo = context.payload.repository
      #       const payload = context.payload
      #       const issueTitle = `Build failed on branch ${context.ref}`;
      #       const issueBody = `
      #         ### Build failed on branch: ${context.ref}

      #         **Commit message**: ${payload.head_commit.message}
      #         **Commit url**: ${payload.head_commit.url}
      #         **Time**: ${payload.head_commit.timestamp}
      #         **Pushed by**: @${payload.pusher.name}
      #         **Details**:
      #       `;

      #       await github.rest.issues.create({
      #         owner: repo.organization,
      #         repo: repo.name,
      #         title: issueTitle,
      #         body: issueBody
      #       });         
