name: "Terraform-bootstrap"
on:
  push:
    branches:
      - main
      - release/*
    paths:
      - "deploy/production/**"
      - "deploy/staging/**"
  pull_request:
    paths:
      - "deploy/production/**"
      - "deploy/staging/**"

env:
  AWS_REGION: us-west-2

# Permissions
permissions:
  contents: read
  id-token: write 
  security-events: write
  actions: write

jobs:
  deploy-ecs:
    name: Deploy to ECS using Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # AWS Credentials with OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/openid_roles
          aws-region: ${{ env.AWS_REGION }}

      # Install the latest version of Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Check Terraform format
      - name: Terraform Format
        run: |
          if terraform fmt -check; then
            echo "Terraform format succeeded"
          else
            echo "Terraform format failed"
            exit 1
          fi

      # Initialize Terraform
      - name: Terraform Init
        run: |
          terraform --version
          if terraform init --upgrade=true; then
            echo "Terraform init succeeded"
          else
            echo "Terraform init failed"
            exit 1
          fi

      # Validate Terraform configuration
      - name: Terraform Validate
        run: |
          if terraform validate; then
            echo "Terraform validate succeeded"
          else
            echo "Terraform validate failed"
            exit 1
          fi

      # Generate Terraform execution plan
      - name: Terraform Plan
        run: |
          if terraform plan -input=false; then
            echo "Terraform plan succeeded"
          else
            echo "Terraform plan failed"
            exit 1
          fi

      # Apply Terraform execution plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
        run: |
          if terraform apply -auto-approve; then
            echo "Terraform apply succeeded"
          else
            echo "Terraform apply failed"
            exit 1
          fi